## Installing Numpy

In [18]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Import Numpy

In [ ]:
import numpy as np

## Array

In [2]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [3]:
print(a[0])

[1 2 3 4]


In [4]:
[[0., 0., 0.], 
[1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

## Creating Array

In [ ]:
np.array()
np.zeros() 
np.ones() 
np.empty() 
np.arange()

In [5]:
import numpy as np
a = np.array([1, 2, 3])

In [6]:
a

array([1, 2, 3])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
print(np.arange(4))
print(np.arange(0,10,2)) #(start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [12]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

## Add, Remove, and Sort

In [ ]:
np.append()
np.delete() 
np.sort()

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [16]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

In [ ]:
ndarray.ndim()
ndarray.size()
ndarray.shape()

In [19]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                         [[0, 1, 2, 3],
                         [4, 5, 6, 7]], 
                         
                         [[0, 1, 2, 3], 
                         [4, 5, 6, 7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [20]:
array_example.ndim

3

In [21]:
array_example.shape

(3, 2, 4)

In [22]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [23]:
arr_one.ndim

2

In [24]:
arr_one.size

5

In [25]:
arr_one.shape

(1, 5)

## Reshape

In [ ]:
np.reshape()

In [27]:
a = np.arange(6) 

print(a)

[0 1 2 3 4 5]


In [28]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [29]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [ ]:
np.newaxis
np.expand_dims

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [31]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [32]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [33]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [35]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [36]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and Slicing

In [37]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [38]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [40]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [41]:
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [42]:
c = a[(a>2) & (a<11)]

print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

Slicing indexing 
np.vstack()
np.hstack() 
np.hsplit() 
.view() 
.copy()

In [43]:
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [44]:
a_1 = np.array([[1, 1], 
               [2, 2]])

In [45]:
a_2 = np.array([[3, 3], 
               [4, 4]])

In [46]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [75]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
                    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [76]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [77]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic array operations

In [81]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [82]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [83]:
b.sum(axis=0)

array([3, 3])

In [84]:
b.sum(axis=1)

array([2, 4])

In [85]:
data = np.array([1, 2])
data 

array([1, 2])

In [86]:
ones = np.ones(2)
ones

array([1., 1.])

In [87]:
data + ones

array([2., 3.])

In [88]:
data * data

array([1, 4])

In [89]:
data / data

array([1., 1.])

## Broadcasting

In [90]:
data * 1.6

array([1.6, 3.2])

In [91]:
data * 2

array([2, 4])

## More Array Operations

In [93]:
A = np.array([[0.45353534, 0.14431448, 0.34340058, 0.55515956], 
             [0.54624892, 0.051485372, 0.40002414, 0.55641231], 
             [0.12692414, 0.824232434, 0.26359324, 0.56917102]])
print(A)

[[0.45353534 0.14431448 0.34340058 0.55515956]
 [0.54624892 0.05148537 0.40002414 0.55641231]
 [0.12692414 0.82423243 0.26359324 0.56917102]]


In [96]:
A.sum()

4.834501535999999

In [97]:
A.min()

0.051485372

In [98]:
A.min(axis=0)

array([0.12692414, 0.05148537, 0.26359324, 0.55515956])

In [99]:
A.max()

0.824232434

In [100]:
A.max(axis=1)

array([0.55515956, 0.55641231, 0.82423243])

In [101]:
A.std()

0.2168918951585063

## Creating Matrices

In [102]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

## Matrix Arithmetic

In [106]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [107]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [108]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [109]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [110]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [116]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [117]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [118]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [119]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [120]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [121]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing anda Reshaping

In [122]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [123]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [124]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [125]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [128]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [129]:
ndarr = np.array([[[1,2], [3,4]],
                [[5,6], [7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [130]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [131]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [132]:
print(np.random.random((4,3,2)))

[[[0.78129969 0.68313943]
  [0.39284924 0.8330885 ]
  [0.32337356 0.5880583 ]]

 [[0.72542504 0.61341184]
  [0.44946414 0.42214917]
  [0.96268688 0.9964522 ]]

 [[0.62419395 0.47503803]
  [0.40320006 0.42216285]
  [0.59817028 0.5084704 ]]

 [[0.75109168 0.80440928]
  [0.33944758 0.2448576 ]
  [0.58166184 0.61070523]]]


## Flatten N-Dimensional Array

In [133]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [134]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

error = (1/n) * np.sum(np.square(observed - prediction))